spring.application.name=craftcart-api
# Database Configuration
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/craftcart_db
spring.datasource.username=craftcart_user
spring.datasource.password=craftcart123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true